galaxy_info:
  author: Goran MekiÄ‡
  description: Common tasks for FreeBSD machines/jails
  issue_tracker_url: https://github.com/mekanix/freebsd-common/issues
  license: BSD
  min_ansible_version: 2.0
  platforms:
    - name: FreeBSD
      versions:
        - all

  galaxy_tags: [freebsd]
    # List tags for your role here, one per line. A tag is
    # a keyword that describes and categorizes the role.
    # Users find roles by searching for tags. Be sure to
    # remove the '[]' above if you add tags to this list.
    #
    # NOTE: A tag is limited to a single word comprised of
    # alphanumeric characters. Maximum 20 tags per role.

dependencies: []
  # List your role dependencies here, one per line.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
